apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ291c2Vy   # base64 encoded (mongouser)
  mongo-root-password: cGFzc3dvcmQ=   # base64 encoded (password)
