apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-media-app
  template:
    metadata:
      labels:
        app: social-media-app
    spec:
      containers:
      - name: social-media-app
        image: social-media-app:1.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-service
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
